import json
import os
from flask import Flask, jsonify, render_template_string, request

app = Flask(__name__)

# Load the pipeline's output.json file generated by drought_analysis.py
OUTPUT_JSON_PATH = os.path.join(os.path.dirname(__file__), "output.json")


def load_pipeline_data():
  if os.path.exists(OUTPUT_JSON_PATH):
    try:
      with open(OUTPUT_JSON_PATH, "r") as f:
        data = json.load(f)
        # Convert list of regions into a dictionary mapped by region name for quick lookup
        return {r["region"]: r for r in data.get("regions", [])}
    except Exception:
      pass
  return {}


HTML_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
    <title>Drought Prediction System</title>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <style>
        body { font-family: Arial, sans-serif; background-color: #f4f7f6; display: flex; justify-content: center; align-items: center; min-height: 100vh; margin: 0; }
        .card { background: white; padding: 25px; border-radius: 10px; box-shadow: 0 4px 10px rgba(0,0,0,0.1); width: 420px; text-align: center; }
        select, input { width: 100%; padding: 10px; margin: 10px 0; border: 1px solid #ccc; border-radius: 5px; box-sizing: border-box; }
        button { background-color: #0070f3; color: white; border: none; padding: 10px; width: 100%; border-radius: 5px; cursor: pointer; font-size: 16px; }
        button:hover { background-color: #0051cc; }
        #result { margin-top: 15px; font-weight: bold; color: #333; text-align: left; font-size: 14px; line-height: 1.5; }
        .chart-container { position: relative; margin-top: 20px; height: 180px; width: 100%; }
    </style>
</head>
<body>
    <div class="card">
        <h2>Drought Early-Warning</h2>
        <p>Select Region & Input Override (Optional)</p>
        
        <select id="region">
            <option value="Tigray">Tigray</option>
            <option value="Amhara">Amhara</option>
            <option value="Oromia">Oromia</option>
            <option value="SNNPR">SNNPR</option>
        </select>

        <input type="number" id="rainfall" step="0.1" placeholder="Override recent rainfall in mm (leave blank to use pipeline data)">
        <button onclick="analyzeRegion()">Fetch Pipeline Analysis</button>
        
        <div id="result"></div>
        
        <div class="chart-container">
            <canvas id="riskChart"></canvas>
        </div>
    </div>

    <script>
        let myChart = null;

        function updateChart(deficitPct, riskLevel) {
            let ctx = document.getElementById('riskChart').getContext('2d');
            let lowVal = Math.max(0, 100 - deficitPct);

            if (myChart) { myChart.destroy(); }

            myChart = new Chart(ctx, {
                type: 'bar',
                data: {
                    labels: ['Deficit %', 'Normal Baseline %'],
                    datasets: [{
                        data: [deficitPct, lowVal],
                        backgroundColor: [riskLevel === 'High' ? '#d9534f' : (riskLevel === 'Medium' ? '#f0ad4e' : '#28a745'), '#28a745'],
                        borderWidth: 1
                    }]
                },
                options: {
                    responsive: true,
                    maintainAspectRatio: false,
                    scales: { y: { beginAtZero: true, max: 100 } },
                    plugins: { legend: { display: false } }
                }
            });
        }

        async function analyzeRegion() {
            let region = document.getElementById('region').value;
            let val = document.getElementById('rainfall').value;
            let resultDiv = document.getElementById('result');
            
            resultDiv.innerText = "Reading pipeline data...";
            
            try {
                let response = await fetch('/predict', {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify({ region: region, rainfall_mm: val ? parseFloat(val) : null })
                });
                let data = await response.json();
                if(response.ok) {
                    let color = data.risk_level === 'High' ? '#d9534f' : (data.risk_level === 'Medium' ? '#f0ad4e' : '#28a745');
                    
                    resultDiv.innerHTML = `
                        <u><b>${data.region} Pipeline Analysis</b></u><br>
                        • Historical Avg: ${data.historical_avg_rainfall_mm} mm<br>
                        • Recent Avg / Input: ${data.recent_avg_rainfall_mm} mm<br>
                        • Deficit: <b>${data.deficit_pct}%</b><br>
                        • Risk Level: <span style="color: ${color}; font-size: 16px;"><b>${data.risk_level} Risk</b></span>
                    `;
                    
                    updateChart(data.deficit_pct, data.risk_level);
                } else {
                    resultDiv.innerText = data.error || "Analysis failed.";
                }
            } catch (err) {
                resultDiv.innerText = "Error connecting to server.";
            }
        }
    </script>
</body>
</html>
"""


@app.route("/")
def home():
  return render_template_string(HTML_TEMPLATE)


@app.route("/predict", methods=["POST"])
def predict():
  try:
    req_data = request.get_json()
    region = req_data.get("region", "Tigray")
    custom_rainfall = req_data.get("rainfall_mm")

    # Load data directly from output.json
    pipeline_data = load_pipeline_data()

    if region not in pipeline_data:
      return (
          jsonify({
              "error": (
                  "Region data not found in output.json. Run pipeline"
                  " analysis first."
              )
          }),
          400,
      )

    reg_info = pipeline_data[region]
    historical_avg = reg_info["historical_avg_rainfall_mm"]

    # If user provided a custom input override, recalculate deficit and risk on the fly
    if custom_rainfall is not None:
      recent_avg = custom_rainfall
      if historical_avg > 0:
        deficit_pct = round(
            ((historical_avg - recent_avg) / historical_avg) * 100, 1
        )
      else:
        deficit_pct = 0.0
      deficit_pct = max(0.0, deficit_pct)

      if deficit_pct > 50:
        risk_level = "High"
      elif deficit_pct > 25:
        risk_level = "Medium"
      else:
        risk_level = "Low"
    else:
      # Otherwise use the exact pre-calculated values straight from output.json
      recent_avg = reg_info["recent_avg_rainfall_mm"]
      deficit_pct = reg_info["deficit_pct"]
      risk_level = reg_info["risk_level"]

    return jsonify({
        "region": region,
        "historical_avg_rainfall_mm": historical_avg,
        "recent_avg_rainfall_mm": recent_avg,
        "deficit_pct": deficit_pct,
        "risk_level": risk_level,
    })
  except Exception as e:
    return jsonify({"error": str(e)}), 400


if __name__ == "__main__":
  app.run(debug=True, port=5002)
