import json
import os
from flask import Flask, jsonify, render_template_string, request

app = Flask(__name__)

# Load the pipeline's output.json file generated by drought_analysis.py
OUTPUT_JSON_PATH = os.path.join(os.path.dirname(__file__), "output.json")


def load_pipeline_data():
  if os.path.exists(OUTPUT_JSON_PATH):
    try:
      with open(OUTPUT_JSON_PATH, "r") as f:
        data = json.load(f)
        return {r["region"]: r for r in data.get("regions", [])}
    except Exception:
      pass
  return {}


HTML_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
    <title>Drought Prediction System</title>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <style>
        body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; background-color: #f4f7f6; display: flex; justify-content: center; align-items: center; min-height: 100vh; margin: 0; }
        .card { background: white; padding: 30px; border-radius: 12px; box-shadow: 0 6px 15px rgba(0,0,0,0.08); width: 420px; text-align: center; }
        h2 { color: #2c3e50; margin-bottom: 5px; }
        p { color: #7f8c8d; font-size: 14px; margin-bottom: 20px; }
        
        /* Modern Attractive Dropdown Styling */
        .select-wrapper { position: relative; margin-bottom: 15px; }
        select { 
            width: 100%; 
            padding: 12px 15px; 
            background-color: #fdfdfd; 
            border: 1.5px solid #dcdde1; 
            border-radius: 8px; 
            font-size: 15px; 
            color: #2f3640; 
            appearance: none; 
            -webkit-appearance: none; 
            -moz-appearance: none; 
            cursor: pointer; 
            transition: all 0.3s ease;
        }
        select:hover { border-color: #718093; }
        select:focus { border-color: #0070f3; outline: none; box-shadow: 0 0 0 3px rgba(0, 112, 243, 0.15); background-color: #fff; }
        
        /* Custom dropdown arrow indicator */
        .select-wrapper::after {
            content: '▼';
            font-size: 11px;
            color: #718093;
            position: absolute;
            right: 15px;
            top: 50%;
            transform: translateY(-50%);
            pointer-events: none;
        }

        input { width: 100%; padding: 12px 15px; margin-bottom: 15px; border: 1.5px solid #dcdde1; border-radius: 8px; font-size: 15px; box-sizing: border-box; transition: all 0.3s ease; }
        input:focus { border-color: #0070f3; outline: none; box-shadow: 0 0 0 3px rgba(0, 112, 243, 0.15); }

        button { background-color: #0070f3; color: white; border: none; padding: 12px; width: 100%; border-radius: 8px; cursor: pointer; font-size: 16px; font-weight: 600; transition: background-color 0.2s; }
        button:hover { background-color: #0051cc; }
        
        #result { margin-top: 20px; font-weight: 500; color: #2f3640; text-align: left; font-size: 14px; line-height: 1.6; background: #f8f9fa; padding: 12px; border-radius: 8px; border-left: 4px solid #0070f3; }
        .chart-container { position: relative; margin-top: 20px; height: 180px; width: 100%; }
    </style>
</head>
<body>
    <div class="card">
        <h2>Drought Early-Warning</h2>
        <p>Select Region & Input Override (Optional)</p>
        
        <div class="select-wrapper">
            <select id="region">
                <option value="Tigray">Tigray Region</option>
                <option value="Amhara">Amhara Region</option>
                <option value="Oromia">Oromia Region</option>
                <option value="SNNPR">SNNPR Region</option>
            </select>
        </div>

        <input type="number" id="rainfall" step="0.1" placeholder="Override recent rainfall in mm (optional)">
        <button onclick="analyzeRegion()">Fetch Pipeline Analysis</button>
        
        <div id="result">Select a region and click analyze to view pipeline results.</div>
        
        <div class="chart-container">
            <canvas id="riskChart"></canvas>
        </div>
    </div>

    <script>
        let myChart = null;

        function updateChart(deficitPct, riskLevel) {
            let ctx = document.getElementById('riskChart').getContext('2d');
            let lowVal = Math.max(0, 100 - deficitPct);

            if (myChart) { myChart.destroy(); }

            myChart = new Chart(ctx, {
                type: 'bar',
                data: {
                    labels: ['Deficit %', 'Normal Baseline %'],
                    datasets: [{
                        data: [deficitPct, lowVal],
                        backgroundColor: [riskLevel === 'High' ? '#d9534f' : (riskLevel === 'Medium' ? '#f0ad4e' : '#28a745'), '#28a745'],
                        borderWidth: 1
                    }]
                },
                options: {
                    responsive: true,
                    maintainAspectRatio: false,
                    scales: { y: { beginAtZero: true, max: 100 } },
                    plugins: { legend: { display: false } }
                }
            });
        }

        async function analyzeRegion() {
            let region = document.getElementById('region').value;
            let val = document.getElementById('rainfall').value;
            let resultDiv = document.getElementById('result');
            
            resultDiv.innerText = "Reading pipeline data...";
            
            try {
                let response = await fetch('/predict', {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify({ region: region, rainfall_mm: val ? parseFloat(val) : null })
                });
                let data = await response.json();
                if(response.ok) {
                    let color = data.risk_level === 'High' ? '#d9534f' : (data.risk_level === 'Medium' ? '#f0ad4e' : '#28a745');
                    
                    resultDiv.innerHTML = `
                        <u><b>${data.region} Pipeline Analysis</b></u><br>
                        • Historical Avg: ${data.historical_avg_rainfall_mm} mm<br>
                        • Recent Avg / Input: ${data.recent_avg_rainfall_mm} mm<br>
                        • Deficit: <b>${data.deficit_pct}%</b><br>
                        • Risk Level: <span style="color: ${color}; font-size: 15px;"><b>${data.risk_level} Risk</b></span>
                    `;
                    
                    updateChart(data.deficit_pct, data.risk_level);
                } else {
                    resultDiv.innerText = data.error || "Analysis failed.";
                }
            } catch (err) {
                resultDiv.innerText = "Error connecting to server.";
            }
        }
    </script>
</body>
</html>
"""


@app.route("/")
def home():
  return render_template_string(HTML_TEMPLATE)


@app.route("/predict", methods=["POST"])
def predict():
  try:
    req_data = request.get_json()
    region = req_data.get("region", "Tigray")
    custom_rainfall = req_data.get("rainfall_mm")

    pipeline_data = load_pipeline_data()

    if region not in pipeline_data:
      return (
          jsonify({
              "error": (
                  "Region data not found in output.json. Run pipeline"
                  " analysis first."
              )
          }),
          400,
      )

    reg_info = pipeline_data[region]
    historical_avg = reg_info["historical_avg_rainfall_mm"]

    if custom_rainfall is not None:
      recent_avg = custom_rainfall
      if historical_avg > 0:
        deficit_pct = round(
            ((historical_avg - recent_avg) / historical_avg) * 100, 1
        )
      else:
        deficit_pct = 0.0
      deficit_pct = max(0.0, deficit_pct)

      if deficit_pct > 50:
        risk_level = "High"
      elif deficit_pct > 25:
        risk_level = "Medium"
      else:
        risk_level = "Low"
    else:
      recent_avg = reg_info["recent_avg_rainfall_mm"]
      deficit_pct = reg_info["deficit_pct"]
      risk_level = reg_info["risk_level"]

    return jsonify({
        "region": region,
        "historical_avg_rainfall_mm": historical_avg,
        "recent_avg_rainfall_mm": recent_avg,
        "deficit_pct": deficit_pct,
        "risk_level": risk_level,
    })
  except Exception as e:
    return jsonify({"error": str(e)}), 400


if __name__ == "__main__":
  app.run(debug=True, port=5002)
